### ISSUE TITLE
[fix] Make cursor not affect the width of the element

### ISSUE THREAD

**Issue by fabianmossberg** [henriquehbr/svelte-typewriter#42] opened 2021-03-04 15:34 UTC
Now, when using the cursor on a centered text, it's causing a little jump just as the cursor is removed.

https://user-images.githubusercontent.com/1999142/109987778-360d0c80-7d07-11eb-8a97-d5251ef139df.mov

It would be great if it was possible to not let it affect the width of the element.

**Comment by henriquehbr** [comment] 2021-03-06 18:43
Indeed, i'm not sure, but my shot is that it has something to do with CSS positioning, which makes the cursor as part of the element, instead of being irrelevant towards the text boundaries

I'll try to reproduce this locally with different scenarios and fix it to avoid such behaviour, if you feel like, you can share a reproduction of the repository you're working on, this might help on the resolution of the problem (if it's not too generalistic)

Thanks again for your valuable report!

**Comment by fabianmossberg** [comment] 2021-03-07 17:50
https://svelte.dev/repl/c4dfd58d17f64618b91e8ca824d80f14?version=3.35.0

**Comment by henriquehbr** [comment] 2021-11-06 13:03
Hey @fabianmossberg, i just re-checked your REPL after releasing version 3.0.0 and seems to be fixed, can you confirm, please?

**Comment by henriquehbr** [comment] 2022-08-01 00:17
As the project is migrating to sourcehut, i'll be closing this issue, if you feel that the reported problem haven't been solved, feel free to reopen it [here](https://todo.sr.ht/~henriquehbr/svelte-typewriter), otherwise, you can just ignore this message

**Closed by henriquehbr** 2022-08-01 00:17 UTC
Labels: bug, need feedback
