### ISSUE TITLE
Jest doesn't detect in a good way the module

### ISSUE THREAD

**Issue by alcibiadesc** [henriquehbr/svelte-typewriter#73] opened 2022-02-11 01:36 UTC
# First Bug
``` 
Cannot find module 'svelte-typewriter' from 'src/components/pages/Landing/Landing.svelte'
```

>Steps to fix this problem: 

Add in the package.json of "./node_modules/svelte-typewriter" this:
```
{
main": "src/Typewriter.svelte"
}
```

# Second Bug:
```
Details:

    /Users/userName/github/repoName/node_modules/svelte-typewriter/src/Typewriter.svelte:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){<script>

SyntaxError: Unexpected token '<'
```

>Steps to fix this problem: WIP

**Comment by henriquehbr** [comment] 2022-02-11 02:11
Would you mind sharing a link to a repository/branch where i could reproduce this issue, so i have a better understanding of your use case and what exactly you're trying to do?

**Comment by alcibiadesc** [comment] 2022-02-11 02:18
@henriquehbr  Yes, of course: 

https://github.com/alcibiadesc/linkerman

```
npx degit alcibiadesc/linkerman Testing
```

And when you install all: 

```
npm test
```

And gonna appear a bug in Landing.svelte that have Typewriter.svelte

**Comment by henriquehbr** [comment] 2022-02-11 02:28
I've cloned the repo, and ran the tests, and got the following output:

```
> linkerman@0.0.1 test
> jest src

 PASS  src/components/atoms/Button/Button.test.js
 PASS  src/components/atoms/Footer/Footer.test.js
 PASS  src/components/molecules/Box/Box.test.js
 PASS  src/components/atoms/Title/Title.test.js

Snapshot Summary
 › 1 snapshot file obsolete from 1 test suite. To remove it, run `npm test -- -u`.
   ↳   • src/components/pages/__snapshots__/Landing.test.js.snap

Test Suites: 1 skipped, 4 passed, 4 of 5 total
Tests:       1 skipped, 13 passed, 14 total
Snapshots:   1 file obsolete, 0 total
Time:        3.02 s
Ran all test suites matching /src/i.
```

Correct me if i'm missing something, i'm not sure if the warning above is related to the bug you mentioned, but i didn't got any of the error messages on your issue report

**Comment by alcibiadesc** [comment] 2022-02-11 02:30
> I've cloned the repo, and ran the tests, and got the following output:
> 
> ```
> > linkerman@0.0.1 test
> > jest src
> 
>  PASS  src/components/atoms/Button/Button.test.js
>  PASS  src/components/atoms/Footer/Footer.test.js
>  PASS  src/components/molecules/Box/Box.test.js
>  PASS  src/components/atoms/Title/Title.test.js
> 
> Snapshot Summary
>  › 1 snapshot file obsolete from 1 test suite. To remove it, run `npm test -- -u`.
>    ↳   • src/components/pages/__snapshots__/Landing.test.js.snap
> 
> Test Suites: 1 skipped, 4 passed, 4 of 5 total
> Tests:       1 skipped, 13 passed, 14 total
> Snapshots:   1 file obsolete, 0 total
> Time:        3.02 s
> Ran all test suites matching /src/i.
> ```
> 
> Correct me if i'm missing something, i'm not sure if the warning above is related to the bug you mentioned, but i didn't got any of the error messages on your issue report

Ouch sorry, I didn't push the version with the bug hahah give me a second

**Comment by alcibiadesc** [comment] 2022-02-11 02:33
@henriquehbr clone the repo again, and sorry about that mistake :( 

now, this gonna be the error: 

```
FAIL  src/components/pages/Landing/Landing.test.js
  ● Test suite failed to run

    Cannot find module 'svelte-typewriter' from 'src/components/pages/Landing/Landing.svelte'

    Require stack:
      src/components/pages/Landing/Landing.svelte
      src/components/pages/Landing/Landing.test.js

      2 | 	import Box from '$molecules/Box';
      3 | 	import Title from '$atoms/Title';
    > 4 | 	import Typewriter from 'svelte-typewriter';
        | 	                 ^
      5 | </script>
      6 |
      7 | <section class="flex flex-wrap place-content-center sm:mt-20">

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/components/pages/Landing/Landing.svelte:4:19)
```

**Comment by alcibiadesc** [comment] 2022-02-11 02:35
To forward about this first bug I added in Typewriter "package.json" a 

```
{
main": "src/Typewriter.svelte"
}
```

And later the bug gonna be:

```
 FAIL  src/components/pages/Landing/Landing.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/alcibiades/github/Testing2/node_modules/svelte-typewriter/src/Typewriter.svelte:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){<script>
                                                                                      ^

    SyntaxError: Unexpected token '<'

      2 | 	import Box from '$molecules/Box';
      3 | 	import Title from '$atoms/Title';
    > 4 | 	import Typewriter from 'svelte-typewriter';
        | 	                 ^
      5 | </script>
      6 |
      7 | <section class="flex flex-wrap place-content-center sm:mt-20">

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/components/pages/Landing/Landing.svelte:4:19)
```

**Comment by henriquehbr** [comment] 2022-02-11 03:05
Just did some research on the matter, and i think i could move a bit closer to a solution, can you confirm if renaming your `.babelrc` to `babel.config.cjs` returns a different error? it worked for me

Source: this [answer](https://stackoverflow.com/a/61677022/9182121), and the first comment of this another [answer](https://stackoverflow.com/a/61948485/9182121) on StackOverflow

**Comment by henriquehbr** [comment] 2022-02-11 03:07
Sorry, almost forgot to include the output of the new error being returned:

```
> linkerman@0.0.1 test
> jest src

 PASS  src/components/atoms/Title/Title.test.js
 PASS  src/components/atoms/Footer/Footer.test.js
 PASS  src/components/molecules/Box/Box.test.js
 PASS  src/components/atoms/Button/Button.test.js
 FAIL  src/components/pages/Landing/Landing.test.js
  ● Test suite failed to run

    Cannot find module './../../../mocks/MockComponent.svelte' from 'src/components/pages/Landing/Landing.test.js'

      2 |
      3 | import Landing from './Landing.svelte';
    > 4 | import MockComponent from './../../../mocks/MockComponent.svelte';
        | ^
      5 |
      6 | /*
      7 | jest.mock('svelte-typewriter', () => ({

      at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
      at Object.<anonymous> (src/components/pages/Landing/Landing.test.js:4:1)

Test Suites: 1 failed, 4 passed, 5 total
Tests:       13 passed, 13 total
Snapshots:   0 total
Time:        2.976 s
Ran all test suites matching /src/i.
```

**Comment by alcibiadesc** [comment] 2022-02-11 03:08
> Sorry, almost forgot to include the output of the new error being returned:
> 
> ```
> > linkerman@0.0.1 test
> > jest src
> 
>  PASS  src/components/atoms/Title/Title.test.js
>  PASS  src/components/atoms/Footer/Footer.test.js
>  PASS  src/components/molecules/Box/Box.test.js
>  PASS  src/components/atoms/Button/Button.test.js
>  FAIL  src/components/pages/Landing/Landing.test.js
>   ● Test suite failed to run
> 
>     Cannot find module './../../../mocks/MockComponent.svelte' from 'src/components/pages/Landing/Landing.test.js'
> 
>       2 |
>       3 | import Landing from './Landing.svelte';
>     > 4 | import MockComponent from './../../../mocks/MockComponent.svelte';
>         | ^
>       5 |
>       6 | /*
>       7 | jest.mock('svelte-typewriter', () => ({
> 
>       at Resolver.resolveModule (node_modules/jest-resolve/build/resolver.js:324:11)
>       at Object.<anonymous> (src/components/pages/Landing/Landing.test.js:4:1)
> 
> Test Suites: 1 failed, 4 passed, 5 total
> Tests:       13 passed, 13 total
> Snapshots:   0 total
> Time:        2.976 s
> Ran all test suites matching /src/i.
> ```

No worry, you can delete that route (was a try to mock the component)

**Comment by henriquehbr** [comment] 2022-02-11 03:11
Commenting it fixed the issue, now all tests are passing as expected, so i guess we can consider https://github.com/henriquehbr/svelte-typewriter/issues/73#issuecomment-1035840814 as the solution for this?

**Comment by alcibiadesc** [comment] 2022-02-11 03:13
> Commenting it fixed the issue, now all tests are passing as expected, so i guess we can consider [#73 (comment)](https://github.com/henriquehbr/svelte-typewriter/issues/73#issuecomment-1035840814) as the solution for this?
```
❯ jest
 PASS  src/components/atoms/Footer/Footer.test.js
 PASS  src/components/atoms/Button/Button.test.js
 PASS  src/components/molecules/Box/Box.test.js
 PASS  src/components/atoms/Title/Title.test.js
``

I deleted that file Landing.test.js (because I use test.svelte)
Yesssssssss!!! thank so much, was weird.

**Comment by henriquehbr** [comment] 2022-02-11 03:16
I'll submit a patch setting `src/Typewriter.svelte` as the `main` field on `package.json` right away, many thanks for reporting this!

**Comment by henriquehbr** [comment] 2022-02-11 03:42
@alcibiadesc I'm thinking about adding an entry to the readme FAQ section regarding this problem, to prevent future users from struggling with the same problems, i came up with the following:

> #### Test suite failed to run: SyntaxError: Unexpected token '<'
> This happens because Jest cannot parse Svelte syntax right away, it must be transpiled by Babel beforehand, therefore, we must tell Jest to ignore `node_modules` as a whole (as it can contain other Svelte components, or files that aren't recognized by Jest), this can be done by setting the `transformIgnorePatterns` property on your Jest configuration, example below:
>
> ```js
> // jest.config.js
> module.exports = {
>     transformIgnorePatterns: ["node_modules"]
> }
> ```

I did my best on trying to explain the problem and provide the solution for it, do you think it's good to go, or is there any misinformation on the text that i wasn't aware of?

**Comment by henriquehbr** [comment] 2022-02-11 04:00
A fix for this was published under version [3.0.0-alpha.11](https://github.com/henriquehbr/svelte-typewriter/blob/main/CHANGELOG.md#300-alpha11---2022-02-11) and is now available on npm

**Closed by henriquehbr** 2022-02-11 04:00 UTC

**Comment by alcibiadesc** [comment] 2022-02-11 09:44
> @alcibiadesc I'm thinking about adding an entry to the readme FAQ section regarding this problem, to prevent future users from struggling with the same problem, i came up with the following:
> 
> 
> 
> > #### Test suite failed to run: SyntaxError: Unexpected token '<'
> 
> > This happens because Jest cannot parse Svelte syntax right away, it must be transpiled by Babel beforehand, therefore, we must tell Jest to ignore `node_modules` as a whole (as it can contain other Svelte components, or files that aren't recognized by Jest), this can be done by setting the `transformIgnorePatterns` property on your Jest configuration, example below:
> 
> >
> 
> > ```js
> 
> > // jest.config.js
> 
> > module.exports = {
> 
> >     transformIgnorePatterns: ["node_modules"]
> 
> > }
> 
> > ```
> 
> 
> 
> I did my best on trying to explain the problem and provide the solution for it, do you think it's good to go, or is there any misinformation on the text that i wasn't aware of?

It's perfect! 

Add the another option just in case the user have the config of jest in the package json. And is better focus the folder because the default behavior of jest is ignore node_modules in general

// package.json
> 
> 
> >     "transformIgnorePatterns": ["node_modules/svelte-typewriter"]
> 
> 
> > ```

And just in case the weir bug relative about change .babelrc to babel.config.cjs

Whit the template of config 😊

**Comment by alcibiadesc** [comment] 2022-02-11 09:59
Fyi. The discord link about bonfire is broken @henriquehbr ☺️

**Comment by henriquehbr** [comment] 2022-02-11 10:12
At first, i thought that just adding `node_modules` directory on `transformIgnorePatterns` would suffice, but after close inspection on the documentation, it turns out that specifying `svelte-typewriter` is indeed required, i'll correct this silly mistake and include the weird babel config bug on the FAQ

Speaking about Vite, i think this has to do with the fact it (and some other modern build tools) deals with all this hassle under the hood

Thanks about the discord heads up! i'll generate a new invite link and send it to you :)
